# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
sudo: false
warnings_are_errors: true

env:
  global:
  - NOT_CRAN: true
  - MAKEFLAGS="-j8"

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    service: mysql
    addons:
      apt:
        packages:
          - libmysqlclient-dev
  - os: linux
    r: devel
  - os: linux
    r: oldrel
  - os: linux
    r: 3.2
  - os: osx
    osx_image: xcode8.3
    before_install:
      - brew install mysql
      - mysql.server start
  - os: osx
    osx_image: xcode8.3
    disable_homebrew: true
    r_check_args: '--no-tests'
    before_script: 'echo no sql server, only testing build'
  - os: osx
    osx_image: beta-xcode7.3
    disable_homebrew: true
    r_check_args: '--no-tests'
    before_script: 'echo no sql server, only testing build'


r_packages:
  - covr

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - travis_retry mysql -e "CREATE DATABASE IF NOT EXISTS test; ALTER DATABASE test CHARACTER SET 'utf8mb4'; FLUSH PRIVILEGES;" -uroot
  - travis_retry mysql -e "CREATE USER '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot || true
  - travis_retry mysql -e "GRANT ALL PRIVILEGES ON test.* TO '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
