language: r
cache: packages
latex: false

env:
  global:
  - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      service: mysql
      addons:
        apt:
          packages:
            - libmariadbclient-dev
    - os: linux
      dist: trusty
      sudo: false
      env: R_CODECOV=true
      service: mysql
      addons:
        apt:
          packages:
            - libmysqlclient-dev
    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew install mariadb
        - mysql.server start
        - mariadb_config --cflags
        - mariadb_config --libs
        - ls -l /usr/lib
      script:
        - R -q -e 'devtools::install()'
        - R -q -e 'con <- DBI::dbConnect(RMariaDB::MariaDB(), dbname = "test"); DBI::dbGetQuery(con, "SELECT 1")'
    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew install mysql
        - mysql.server start
    - os: osx
      osx_image: xcode8.3
      disable_homebrew: true
      r_check_args: '--no-tests'
      before_script: 'echo no sql server, only testing build'
    - os: osx
      osx_image: beta-xcode7.3
      disable_homebrew: true
      r_check_args: '--no-tests'
      before_script: 'echo no sql server, only testing build'

r_github_packages:
  - rstats-db/DBI@production
  - rstats-db/DBItest@production

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - travis_retry mysql -e "CREATE DATABASE IF NOT EXISTS test; FLUSH PRIVILEGES;" -uroot
  - travis_retry mysql -e "CREATE USER '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot || true
  - travis_retry mysql -e "GRANT ALL PRIVILEGES ON test.* TO '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
