language: r
cache: packages
latex: false

env:
  global:
  - MAKEFLAGS="-j8"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      service: mysql
      addons:
        apt:
          packages:
            - libmariadbclient-dev
    - os: linux
      dist: trusty
      sudo: false
      env: R_CODECOV=true
      service: mysql
      addons:
        apt:
          packages:
            - libmysqlclient-dev

r_github_packages:
  - rstats-db/DBI@production
  - rstats-db/DBItest@production

r_packages:
  - covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - travis_retry mysql -e "CREATE DATABASE IF NOT EXISTS test; ALTER DATABASE test CHARACTER SET 'utf8mb4'; FLUSH PRIVILEGES;" -uroot
  - travis_retry mysql -e "CREATE USER '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot || true
  - travis_retry mysql -e "GRANT ALL PRIVILEGES ON test.* TO '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
