# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install mysql && mysql.server start; fi
- R -q -e 'install.packages("remotes"); remotes::install_github("r-lib/remotes")'
- R -q -e 'remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
- mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
- mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;" -uroot

install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'

before_script:
- R -q -e 'tic::before_script()'
- travis_retry mysql -e "CREATE DATABASE IF NOT EXISTS test; ALTER DATABASE test CHARACTER SET 'utf8'; FLUSH PRIVILEGES;" -uroot
- travis_retry mysql -e "CREATE USER '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot || true
- travis_retry mysql -e "GRANT ALL PRIVILEGES ON test.* TO '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot

script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: false
cache: packages
latex: false
fortran: false
pandoc: false

#stages: test, full
stages:
- name: test
- name: full
  if: branch = master

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - _R_CHECK_SYSTEM_CLOCK_=false
  - MAKEFLAGS="-j 2"
  - R_CHECK_ARGS="--no-manual --as-cran"

#addons
addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libmagick++-dev
    - libssh2-1-dev

#jobs
matrix:
  include:
  - os: linux
    r: devel
  - os: linux
    r: 3.2
  - stage: full
    os: osx
  - os: osx
    osx_image: xcode8.3
    disable_homebrew: true
    env:
      - R_CHECK_ARGS="--no-manual --no-tests"
    before_script: 'echo no sql server, only testing build'
  - os: osx
    osx_image: xcode7.3
    disable_homebrew: true
    env:
      - R_CHECK_ARGS="--no-manual --no-tests"
    before_script: 'echo no sql server, only testing build'
  - os: linux
    r: release
    pandoc: true
    env:
    - BUILD_PKGDOWN=true
    before_deploy: R -q -e 'tic::before_deploy()'
    deploy:
      provider: script
      script: R -q -e 'tic::deploy()'
      on:
        all_branches: true
    after_deploy: R -q -e 'tic::after_deploy()'
  - os: linux
    r: 3.4
  - os: linux
    r: 3.3
  fast_finish: true

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

# Custom parts:

#services
services:
- MySQL
